=== AndreasKarg/soundthesizer-converter/SoundthesizerConverterBackend/SoundthesizerFileSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema id="SoundthesizerFileSchema"
    elementFormDefault="unqualified"
    xmlns:xml="http://www.w3.org/XML/1998/namespace"
    xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="SoundthesizerFileSchema.xsd"
    xmlns:st="SoundthesizerFileSchema.xsd"
>
  <complexType name="dependency">
    <sequence>
      <element minOccurs="0" maxOccurs="unbounded" name="refpoint">
        <complexType>
          <attribute name="x" type="float" use="required"/>
          <attribute name="y" type="float" use="required"/>
        </complexType>
      </element>
      <element name="dependency" type="st:dependency" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="value" type="string"/>
    <attribute name="operator">
      <simpleType>
        <restriction base="string">
          <enumeration value="add"/>
          <enumeration value="subtract"/>
          <enumeration value="multiply"/>
          <enumeration value="divide"/>
          <enumeration value="modulo"/>
        </restriction>
      </simpleType>
    </attribute>
  </complexType>

  <complexType name="trigger_dependency">
    <complexContent>
      <extension base="st:dependency">
        <attribute name="direction" use="required">
          <simpleType>
            <restriction base="string">
              <enumeration value="up"/>
              <enumeration value="down"/>
              <enumeration value="both"/>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </complexContent>
  </complexType>
  
  <element name="soundset">
    <complexType>
      <sequence>
        <element name="sound" minOccurs="1" maxOccurs="unbounded">
          <complexType>
            <all>
              <element name="file">
                <complexType>
                  <attribute name="name" type="string" use="required"/>
                </complexType>
              </element>
              <element name="volume" type="st:dependency" minOccurs="0" maxOccurs="1"/>
              <element name="pan" type="st:dependency" minOccurs="0" maxOccurs="1"/>
              <element name="frequency" type="st:dependency" minOccurs="0" maxOccurs="1"/>
              <element name="trigger" type="st:trigger_dependency" minOccurs="0" maxOccurs="1"/>
            </all>
            <attribute name="name" type="string" use="required"/>
            <attribute name="looped" type="boolean" use="optional" default="true"/>
        </complexType>
        </element>
      </sequence>
    <attribute name="name" type="string" use="required"/>
    </complexType>
  </element>
</schema>

=== AndreasKarg/soundthesizer-converter/SoundthesizerConverterBackend/BR423.xml
<?xml version="1.0"?>
<soundset name="BR 423"
          xmlns ="SoundthesizerFileSchema.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="SoundthesizerFileSchema.xsd SoundthesizerFileSchema.xsd">
  <sound name="Fahren">
    <file name="\Sounds\423_v4\423_Fahren3.wav" />
    <volume value="VIst">
      <refpoint x="0" y="0"/>
      <refpoint x="5" y="1"/>
      <refpoint x="160" y="1"/>
    </volume>
    <pan value="none" />
    <frequency value="VIst">
      <refpoint x="0" y="0" />
      <refpoint x="160" y="1" />
    </frequency>
  </sound>

  <sound name="Umrichterjodeln">
    <file name="\Sounds\423_v4\423_Umrichter_jodel.wav"/>
    <volume operator="multiply">
      <dependency value="Zugkraft_Gesamt">
        <refpoint x="0" y="0"/>
        <refpoint x="72" y="0.7"/>
      </dependency>
      <dependency value="VIst">
        <refpoint x="0" y="1"/>
        <refpoint x="25" y="1"/>
        <refpoint x="50" y="1"/>
        <refpoint x="53" y="0"/>
        <refpoint x="71" y="0"/>
      </dependency>
    </volume>
    <pan value="none"/>
    <frequency value="VIst">
      <refpoint x="10" y="1"/>
      <refpoint x="12" y="1"/>
      <refpoint x="15" y="1"/>
    </frequency>
    <trigger value="VIst" direction="up">
      <refpoint x="0" y="0"/>
      <refpoint x="10" y="0"/>
      <refpoint x="10" y="1"/>
      <refpoint x="20" y="1"/>
    </trigger>
  </sound>

  <sound name="Umrichter_A">
    <file name="\Sounds\423_v4\423_Umrichter_A.wav"/>
    <volume operator="multiply">
      <dependency value="Zugkraft_Gesamt">
        <refpoint x="0" y="0"/>
        <refpoint x="10" y="0"/>
        <refpoint x="72" y="0.7"/>
      </dependency>
      <dependency value="VIst">
        <refpoint x="0" y="1"/>
        <refpoint x="25" y="1"/>
        <refpoint x="50" y="0"/>
      </dependency>
    </volume>
    <pan value="none"/>
    <frequency value="VIst">
      <refpoint x="0" y="1"/>
      <refpoint x="10" y="1"/>
      <refpoint x="10" y="1.2"/>
      <refpoint x="12" y="1.1"/>
      <refpoint x="20" y="1"/>
    </frequency>
    <trigger value="Zugkraft_Gesamt" direction="up">
      <refpoint x="-10" y="0"/>
      <refpoint x="0" y="0"/>
      <refpoint x="0" y="1"/>
      <refpoint x="10" y="1"/>
    </trigger>
  </sound>

  <sound name="Umrichter_C">
    <file name="\Sounds\423_v4\423_Umrichter_C.wav"/>
    <volume operator="multiply">
      <dependency value="Zugkraft_Gesamt">
        <refpoint x="-65" y="1"/>
        <refpoint x="-10" y="1"/>
        <refpoint x="0" y="0"/>
      </dependency>
      <dependency value="VIst">
        <refpoint x="0" y="0"/>
        <refpoint x="5" y="0"/>
        <refpoint x="10" y="0.8"/>
        <refpoint x="20" y="0.7"/>
        <refpoint x="30" y="0"/>
        <refpoint x="57" y="0"/>
        <refpoint x="60" y="0"/>
      </dependency>
    </volume>
    <trigger value="Zugkraft_Gesamt" direction="up">
        <refpoint x="-65" y="1"/>
        <refpoint x="-1" y="1"/>
        <refpoint x="0" y="0"/>
        <refpoint x="10" y="0"/>
    </trigger>
  </sound>

  <sound name="Umrichter_D">
    <file name="\Sounds\423_v4\423_Umrichter_D.wav"/>
    <volume operator="multiply">
      <dependency value="Zugkraft_Gesamt">
        <refpoint x="-65" y="1"/>
        <refpoint x="-10" y="1"/>
        <refpoint x="0" y="0"/>
      </dependency>
      <dependency value="VIst">
        <refpoint x="0" y="0"/>
        <refpoint x="5" y="0"/>
        <refpoint x="10" y="0"/>
        <refpoint x="20" y="0.9"/>
        <refpoint x="47" y="1"/>
        <refpoint x="50" y="0"/>
        <refpoint x="51" y="0"/>
      </dependency>
    </volume>
    <trigger value="Zugkraft_Gesamt" direction="up">
        <refpoint x="-65" y="1"/>
        <refpoint x="-1" y="1"/>
        <refpoint x="0" y="0"/>
        <refpoint x="10" y="0"/>
    </trigger>
  </sound>

  <sound name="Anhaltebrummen">
    <file name="\Sounds\423_v4\423_Umrichter_Anhalten.wav"/>
    <volume operator="multiply">
      <dependency value="Zugkraft_Gesamt">
        <refpoint x="-65" y="1"/>
        <refpoint x="-1" y="1"/>
        <refpoint x="0" y="0"/>
        <refpoint x="100" y="0"/>
      </dependency>
      <dependency value="VIst">
        <refpoint x="0" y="0"/>
        <refpoint x="1" y="1"/>
        <refpoint x="5" y="1"/>
        <refpoint x="6" y="0"/>
      </dependency>
    </volume>
  </sound>

  <sound name="Tatzlager_70">
    <file name="\Sounds\423_v4\423_Getriebe_70kmh.wav" />
    <volume operator="multiply">
      <dependency value="Zugkraft_Gesamt">
        <refpoint x="-65" y="1" />
        <refpoint x="-10" y="1" />
        <refpoint x="0" y="0.5" />
        <refpoint x="10" y="1" />
        <refpoint x="72" y="1" />
      </dependency>
      <dependency value="VIst">
        <refpoint x="0" y="1"/>
        <refpoint x="60" y="1"/>
        <refpoint x="70" y="0.9"/>
        <refpoint x="80" y="0"/>
      </dependency>
    </volume>
    <pan value="none" />
    <frequency value="VIst">
      <refpoint x="-10" y="0"/>
      <refpoint x="0" y="0" />
      <refpoint x="75" y="1" />
      <refpoint x="90" y="1.2"/>
    </frequency>
  </sound>

  <sound name="Tatzlager_120">
    <file name="\Sounds\423_v4\423_Getriebe_120kmh.wav" />
    <volume operator="multiply">
      <dependency value="Zugkraft_Gesamt">
        <refpoint x="-65" y="1" />
        <refpoint x="-10" y="1" />
        <refpoint x="0" y="0.5" />
        <refpoint x="10" y="1" />
        <refpoint x="72" y="1" />
      </dependency>
      <dependency value="VIst">
        <refpoint x="0" y="0"/>
        <refpoint x="60" y="0"/>
        <refpoint x="70" y="0.9"/>
        <refpoint x="80" y="1"/>
      </dependency>
    </volume>
    <pan value="none" />
    <frequency value="VIst">
      <refpoint x="-10" y="0"/>
      <refpoint x="0" y="0" />
      <refpoint x="100" y="1" />
      <refpoint x="160" y="1.6" />
    </frequency>
  </sound>

  <sound name="Anfahrquietschen_Bremse" looped="false">
    <file name="\Sounds\423_v4\423_Bremse_Anfahren.wav"/>
    <trigger value="VIst" direction="up">
      <refpoint x="-10" y="0"/>
      <refpoint x="0" y="0"/>
      <refpoint x="0" y="1"/>
      <refpoint x="10" y="1"/>
    </trigger>
  </sound>
</soundset>
